version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    image: ninefiveblade/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  backend:
    build:
      image: ninefiveblade/foodgram_backend:v1
    restart: always
    volumes:
      - static_value:/app/footgram/static_django/
      - media_value:/app/footgram/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: gunicorn footgram.wsgi:application --bind 0:8000
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_django/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value: