# Generated by Django 3.0 on 2022-07-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(help_text='Выберите ингридиенты рецепта', related_name='reciepe_ingredient', to='cooking.IngredientQuantity', verbose_name='Ингридиенты рецепта'),
        ),
    ]
