# Generated by Django 3.0 on 2022-07-04 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_list_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь избранных рецептов'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(help_text='Выберите ингридиенты рецепта', related_name='reciepe_ingredient', to='cooking.Ingredient', verbose_name='Ингридиенты рецепта'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipe_tag', to='cooking.Tag', verbose_name='Теги по рецептам'),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amount', to='cooking.Ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='favoriterecipes',
            name='recipe',
            field=models.ManyToManyField(related_name='favorite_recipe', to='cooking.Recipe', verbose_name='Избранный рецепт'),
        ),
        migrations.AddField(
            model_name='favoriterecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favotite_list_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь избранных рецептов'),
        ),
    ]
