# Generated by Django 3.0 on 2022-07-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20220710_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='code',
            new_name='color',
        ),
    ]
