# Generated by Django 3.0 on 2022-07-04 20:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20220704_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=colorfield.fields.ColorField(choices=[('Завтрак', '#ff9900'), ('Обед', '#228b22'), ('Ужин', '#9370d8')], default='#FFFFFF', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Код цвета HEX'),
        ),
    ]
