# Generated by Django 2.2.16 on 2022-07-17 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20220717_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Введите количество ингридиента', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингридиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveSmallIntegerField(help_text='Введите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления в минутах'),
        ),
    ]
