# Generated by Django 2.2.16 on 2022-07-01 14:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20220701_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Введите код цвета HEX', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Код цвета HEX'),
        ),
    ]
