# Generated by Django 3.0 on 2022-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20220706_2037'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientquantity',
            constraint=models.UniqueConstraint(fields=('ingredient', 'quantity'), name='unique_ingredient_quantity'),
        ),
    ]
