# Generated by Django 3.0 on 2022-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20220710_1717'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriterecipes',
            constraint=models.UniqueConstraint(fields=('user_id', 'recipe_id'), name='unique_favorites'),
        ),
    ]
