# Generated by Django 3.0 on 2022-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20220704_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(choices=[('Завтрак', '#ff9900'), ('Обед', '#228b22'), ('Ужин', '#9370d8')], max_length=7, unique=True, verbose_name='Код цвета HEX'),
        ),
    ]
