# Generated by Django 3.0 on 2022-07-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20220708_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipes',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favoriterecipes',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='cooking.Recipe', verbose_name='Избранный рецепт'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to='cooking.Recipe', verbose_name='Избранный рецепт'),
            preserve_default=False,
        ),
    ]
