# Generated by Django 3.0 on 2022-07-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20220710_1808'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipes',
            name='unique_favorites',
        ),
    ]
