# Generated by Django 2.2.16 on 2022-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_auto_20220701_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(null=True, related_name='recipe_tag', to='cooking.Recipe'),
        ),
    ]
