# Generated by Django 2.2.16 on 2022-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20220701_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(related_name='recipe_tag', to='cooking.Recipe', verbose_name='Теги по рецептам'),
        ),
    ]
