# Generated by Django 3.0 on 2022-07-04 20:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20220704_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=[('#ff9900', 'Оранжевый'), ('#228b22', 'Зеленый'), ('#9370d8', 'Лиловый')], unique=True, verbose_name='Код цвета HEX'),
        ),
    ]
