# Generated by Django 3.0 on 2022-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_auto_20220709_1926'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.UniqueConstraint(fields=('user_id', 'recipe_id'), name='unique_shoplist'),
        ),
    ]
