# Generated by Django 3.0 on 2022-07-10 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooking', '0006_auto_20220710_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь избранных рецептов'),
        ),
    ]
