# Generated by Django 3.0 on 2022-07-04 20:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_auto_20220704_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=colorfield.fields.ColorField(choices=[('#ff9900', 'orange'), ('#228b22', 'green'), ('#9370d8', 'purple')], default='#FFFFFF', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Код цвета HEX'),
        ),
    ]
