# Generated by Django 3.0 on 2022-07-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220707_1351'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follows',
        ),
    ]
